name: Go Build & Push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.21

      - name: Build
        run: go build -o myapp

      - name: Upload Binary
        uses: actions/upload-artifact@v3
        with:
          name: myapp-binary
          path: ./myapp

